FILESEXTRAPATHS_prepend := "${THISDIR}/linux-obmc:"
SRC_URI += "file://olympus.cfg"
SRC_URI += "file://0001-Added-KCS-interface-support.patch"
SRC_URI += "file://0002-Commented-VUART-support.patch"
SRC_URI += "file://0003-arch-arm-boot-dts-aspeed-bmc-opp-palmetto.patch"
SRC_URI += "file://0004-drivers-iio-adc-aspeed_adc.patch"
SRC_URI += "file://0005-drivers-iio-inkern.patch"
