FILESEXTRAPATHS_append := "${THISDIR}/:"
SRC_URI += "file://0001-arch_arm_include_asm_bootm.h.patch"
SRC_URI += "file://0002-arch_arm_include_asm_setup.h.patch"
SRC_URI += "file://0003-arch_arm_lib_bootm.c.patch"
SRC_URI += "file://0004-arch_arm_lib_interrupts.c.patch"
SRC_URI += "file://0005-inlclude_asm-generic_u-boot.h.patch"
